FROM golang:1.23 AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y git curl watchman btop

# Get Go tools
RUN go install github.com/air-verse/air@latest
RUN go install github.com/a-h/templ/cmd/templ@latest
COPY . .
RUN templ generate
RUN go build -o ./app

FROM golang:1.23
WORKDIR /app

COPY --from=builder /app/app ./app
COPY ./static ./static

EXPOSE 3000

CMD ["./app"]
